// Generated by move-test-gen
// Target: example::vault (deposit, withdraw, flash_borrow, flash_repay, set_fee)
// Tests: 22 total (6 boundary, 4 arithmetic, 3 access, 4 state, 5 economic)
// Expected failures: 7
// Coverage targets: deposit(100%), withdraw(100%), flash_borrow(100%), flash_repay(100%), set_fee(100%)

#[test_only]
module example::vault_tests {
    use example::vault;
    use sui::coin;
    use sui::sui::SUI;

    const ONE_SUI: u64 = 1_000_000_000;      // 1 SUI in MIST

    // ========================
    // BOUNDARY TESTS
    // ========================

    #[test]
    #[expected_failure(abort_code = vault::EZeroAmount)]
    fun test_deposit_boundary_zero() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let coin = coin::mint_for_testing<SUI>(0, &mut ctx);
        vault::deposit(&mut v, coin);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_deposit_boundary_one_mist() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let coin = coin::mint_for_testing<SUI>(1, &mut ctx);
        let shares = vault::deposit(&mut v, coin);
        assert!(shares == 1); // first depositor: shares = amount
        assert!(vault::balance(&v) == 1);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_deposit_boundary_large_amount() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let coin = coin::mint_for_testing<SUI>(1_000_000 * ONE_SUI, &mut ctx); // 1M SUI
        let shares = vault::deposit(&mut v, coin);
        assert!(shares == 1_000_000 * ONE_SUI);
        vault::destroy_for_testing(v);
    }

    #[test]
    #[expected_failure(abort_code = vault::EZeroAmount)]
    fun test_withdraw_boundary_zero_shares() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let coin = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, coin);
        let out = vault::withdraw(&mut v, 0, &mut ctx);
        coin::burn_for_testing(out);
        vault::destroy_for_testing(v);
    }

    #[test]
    #[expected_failure(abort_code = vault::EInsufficientShares)]
    fun test_withdraw_boundary_exceeds_shares() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let coin = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, coin);
        let out = vault::withdraw(&mut v, ONE_SUI + 1, &mut ctx);
        coin::burn_for_testing(out);
        vault::destroy_for_testing(v);
    }


    #[test]
    #[expected_failure(abort_code = vault::EZeroAmount)]
    fun test_flash_borrow_boundary_zero() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let coin = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, coin);
        let (borrowed, receipt) = vault::flash_borrow(&mut v, 0, &mut ctx);
        vault::flash_repay(&mut v, borrowed, receipt);
        vault::destroy_for_testing(v);
    }

    // ========================
    // ARITHMETIC TESTS
    // ========================

    #[test]
    fun test_deposit_arithmetic_share_calculation() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        // First deposit: 1000 SUI -> 1000 SUI worth of shares
        let c1 = coin::mint_for_testing<SUI>(1000 * ONE_SUI, &mut ctx);
        let s1 = vault::deposit(&mut v, c1);
        assert!(s1 == 1000 * ONE_SUI);

        // Second deposit: 500 SUI -> 500 SUI worth of shares (1:1 ratio)
        let c2 = coin::mint_for_testing<SUI>(500 * ONE_SUI, &mut ctx);
        let s2 = vault::deposit(&mut v, c2);
        assert!(s2 == 500 * ONE_SUI);

        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_withdraw_arithmetic_fee_deduction() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(10000, &mut ctx);
        vault::deposit(&mut v, c);

        let out = vault::withdraw(&mut v, 10000, &mut ctx);
        // fee = 10000 * 30 / 10000 = 30
        // net = 10000 - 30 = 9970
        assert!(coin::value(&out) == 9970);

        coin::burn_for_testing(out);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_flash_repay_arithmetic_fee_exact() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(100 * ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);

        let (mut borrowed, receipt) = vault::flash_borrow(&mut v, 10 * ONE_SUI, &mut ctx);
        // fee = 10 SUI * 30 / 10000 = 0.03 SUI = 30_000_000 MIST
        let fee_coin = coin::mint_for_testing<SUI>(30_000_000, &mut ctx);
        borrowed.join(fee_coin);
        vault::flash_repay(&mut v, borrowed, receipt);

        vault::destroy_for_testing(v);
    }

    #[test]
    #[expected_failure(abort_code = vault::EFlashRepayInsufficient)]
    fun test_flash_repay_arithmetic_underpay() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(100 * ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);

        let (borrowed, receipt) = vault::flash_borrow(&mut v, 10 * ONE_SUI, &mut ctx);
        // repay exact amount without fee — should abort
        vault::flash_repay(&mut v, borrowed, receipt);

        vault::destroy_for_testing(v);
    }

    // ========================
    // ACCESS CONTROL TESTS
    // ========================

    #[test]
    fun test_set_fee_with_admin_cap() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let cap = vault::create_admin_cap_for_testing(&mut ctx);

        vault::set_fee(&cap, &mut v, 100); // set to 1%

        // verify by withdrawing: fee should now be 1%
        let c = coin::mint_for_testing<SUI>(10000, &mut ctx);
        vault::deposit(&mut v, c);
        let out = vault::withdraw(&mut v, 10000, &mut ctx);
        // fee = 10000 * 100 / 10000 = 100, net = 9900
        assert!(coin::value(&out) == 9900);

        coin::burn_for_testing(out);
        vault::destroy_admin_cap_for_testing(cap);
        vault::destroy_for_testing(v);
    }

    #[test]
    #[expected_failure(abort_code = vault::EFeeTooHigh)]
    fun test_set_fee_above_max() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let cap = vault::create_admin_cap_for_testing(&mut ctx);

        vault::set_fee(&cap, &mut v, 501); // 5.01% > MAX_FEE_BPS (500)

        vault::destroy_admin_cap_for_testing(cap);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_set_fee_at_max_boundary() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let cap = vault::create_admin_cap_for_testing(&mut ctx);

        vault::set_fee(&cap, &mut v, 500); // exactly MAX_FEE_BPS — should succeed

        vault::destroy_admin_cap_for_testing(cap);
        vault::destroy_for_testing(v);
    }

    // Note: testing set_fee without AdminCap is not a runtime test — Move's type
    // system prevents calling set_fee without passing an &AdminCap reference at
    // compile time. This is documented rather than tested.
    // See: SKILL.md Quality Rule 1 and references/patterns.md §2.1

    // ========================
    // STATE MACHINE TESTS
    // ========================

    #[test]
    fun test_flash_borrow_repay_roundtrip() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);
        let balance_before = vault::balance(&v);

        let (mut borrowed, receipt) = vault::flash_borrow(&mut v, ONE_SUI / 2, &mut ctx);
        // fee = 500_000_000 * 30 / 10000 = 1_500_000 MIST
        let fee = coin::mint_for_testing<SUI>(1_500_000, &mut ctx);
        borrowed.join(fee);
        vault::flash_repay(&mut v, borrowed, receipt);

        // vault should have original balance + fee
        assert!(vault::balance(&v) == balance_before + 1_500_000);

        vault::destroy_for_testing(v);
    }

    #[test]
    #[expected_failure(abort_code = vault::EInsufficientBalance)]
    fun test_flash_borrow_exceeds_balance() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);

        let (borrowed, receipt) = vault::flash_borrow(&mut v, ONE_SUI + 1, &mut ctx);
        vault::flash_repay(&mut v, borrowed, receipt);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_deposit_withdraw_roundtrip() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        let shares = vault::deposit(&mut v, c);
        let out = vault::withdraw(&mut v, shares, &mut ctx);

        // withdraw charges 0.3% fee
        // net = 1_000_000_000 - (1_000_000_000 * 30 / 10000) = 997_000_000
        assert!(coin::value(&out) == 997_000_000);
        assert!(vault::total_shares(&v) == 0);

        coin::burn_for_testing(out);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_multiple_depositors_fair_shares() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        // Alice deposits 1000 SUI
        let c1 = coin::mint_for_testing<SUI>(1000 * ONE_SUI, &mut ctx);
        let s1 = vault::deposit(&mut v, c1);

        // Bob deposits 500 SUI
        let c2 = coin::mint_for_testing<SUI>(500 * ONE_SUI, &mut ctx);
        let s2 = vault::deposit(&mut v, c2);

        // Alice has 2x Bob's shares
        assert!(s1 == 2 * s2);

        vault::destroy_for_testing(v);
    }

    // ========================
    // ECONOMIC TESTS
    // ========================

    #[test]
    fun test_withdraw_fee_dust_pays_zero() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);

        // Withdraw 1 share (1 MIST worth)
        // fee = 1 * 30 / 10000 = 0 (truncated) — zero fee on dust
        let out = vault::withdraw(&mut v, 1, &mut ctx);
        assert!(coin::value(&out) == 1); // full amount, no fee taken

        coin::burn_for_testing(out);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_flash_borrow_dust_fee_zero() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);

        // Borrow 333 MIST: fee = 333 * 30 / 10000 = 0 (truncated)
        // Attacker can borrow and repay with zero fee
        let (borrowed, receipt) = vault::flash_borrow(&mut v, 333, &mut ctx);
        vault::flash_repay(&mut v, borrowed, receipt);

        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_withdraw_fee_at_minimum_payable() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        let c = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);

        // Minimum amount where fee > 0: ceil(10000/30) = 334
        // fee = 334 * 30 / 10000 = 1 (first non-zero fee)
        let out = vault::withdraw(&mut v, 334, &mut ctx);
        assert!(coin::value(&out) == 333); // 334 - 1 = 333

        coin::burn_for_testing(out);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_withdraw_fee_at_max_rate() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);
        let cap = vault::create_admin_cap_for_testing(&mut ctx);

        vault::set_fee(&cap, &mut v, 500); // max: 5%

        let c = coin::mint_for_testing<SUI>(ONE_SUI, &mut ctx);
        vault::deposit(&mut v, c);

        let out = vault::withdraw(&mut v, ONE_SUI, &mut ctx);
        // fee = 1_000_000_000 * 500 / 10000 = 50_000_000 (0.05 SUI)
        assert!(coin::value(&out) == 950_000_000);

        coin::burn_for_testing(out);
        vault::destroy_admin_cap_for_testing(cap);
        vault::destroy_for_testing(v);
    }

    #[test]
    fun test_first_depositor_share_ratio() {
        let mut ctx = tx_context::dummy();
        let mut v = vault::create_for_testing(&mut ctx);

        // First depositor: 1 MIST -> 1 share
        let c1 = coin::mint_for_testing<SUI>(1, &mut ctx);
        let s1 = vault::deposit(&mut v, c1);
        assert!(s1 == 1);

        // Second depositor: 999_999 MIST
        // shares = 999_999 * 1 / 1 = 999_999
        // In this vault, first-depositor inflation is not possible because
        // there is no donate() function. But if balance could be inflated
        // externally (e.g., direct coin transfer), the second depositor
        // would get shares = 999_999 * 1 / (1 + donated_amount), which
        // rounds to 0 for large donations. Protocols should enforce
        // minimum initial deposit to prevent this.
        let c2 = coin::mint_for_testing<SUI>(999_999, &mut ctx);
        let s2 = vault::deposit(&mut v, c2);
        assert!(s2 == 999_999);

        vault::destroy_for_testing(v);
    }
}
